apiVersion: scheduling.k8s.io/v1
# globalDefault: true
kind: PriorityClass
metadata:
  annotations:
    meta.helm.sh/release-name: shakudo-hyperplane
  labels:
    app.kubernetes.io/managed-by: Helm
  name: shakudo-job-default
preemptionPolicy: PreemptLowerPriority
value: 10000
